<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225061733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, price NUMERIC(10, 2) NOT NULL, category VARCHAR(100) NOT NULL, tags JSON DEFAULT NULL, in_stock BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, embedding vector(1536) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_category ON products (category)');
        $this->addSql('CREATE INDEX idx_product_created_at ON products (created_at)');
        $this->addSql('CREATE TABLE search_queries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, keyword VARCHAR(500) NOT NULL, vector vector(1536) DEFAULT NULL, user_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, search_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_search_queries_created_at ON search_queries (created_at)');
        $this->addSql('CREATE INDEX idx_search_queries_user_id ON search_queries (user_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE search_queries');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP EXTENSION IF EXISTS vector');

    }
}
